name: FFmpeg SDK Build (Android + iOS)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Android Config
        run: |
          chmod +x scripts/validate_ffmpeg_config.sh
          scripts/validate_ffmpeg_config.sh configs/ffmpeg_android.conf

      - name: Validate iOS Config
        run: |
          scripts/validate_ffmpeg_config.sh configs/ffmpeg_ios.conf


  android:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y git yasm nasm build-essential pkg-config

      - name: Setup NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip
          echo "NDK=$PWD/android-ndk-r26d" >> $GITHUB_ENV

      - name: Build Dependencies
        run: |
          bash scripts/build-deps-android.sh

      - name: Build FFmpeg Android
        run: |
          bash scripts/build-android.sh

  ios:
    needs: validate
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: brew install yasm nasm pkg-config

      - name: Build Dependencies
        run: |
          bash scripts/build-deps-ios.sh

      - name: Build FFmpeg iOS
        run: |
          bash scripts/build-ios.sh
